### ISSUE TITLE
Please upload 'models' files

### ISSUE THREAD

**Issue by subhash-holla** [hellbell/ADNet#10]
The models folder does not contain files like net_init.mat, imagenet-vgg-m-conv1-3.mat, etc. Please upload the files to help us reproduce the training results.
Thank You.

**Comment by aseuteurideu** [comment]
As I tried, net_init.mat is generated in the code. And I downloaded imagenet-vgg-m-conv1-3.mat from https://github.com/HyeonseobNam/MDNet/blob/master/models/imagenet-vgg-m-conv1-3.mat
