### ISSUE TITLE
about your example model

### ISSUE THREAD

**Issue by sseung0703** [hellbell/ADNet#2]
I think uploaded model is not same with your latest model

model's layer is not same with that you explain in paper and also accuracy is lower than paper's.

would you please check your model and re-upload. I want your model for comparing with my one in same experiment condition.

**Comment by SlovenXing** [comment]
I also find this problem. would you please re-upload your model?

**Comment by hellbell** [comment]
I uploaded a wrong model and updated it. Thanks!

**Comment by chenyanyin** [comment]
Excuse me, do you test the updated model? Do you reproduce the results in paper?
