### ISSUE TITLE
Undefined function or variable 'test_demo'

### ISSUE THREAD

**Issue by ZongweiZhou1** [hellbell/ADNet#4]
Hi, I meet this error 
 'Undefined function or variable 'test_demo''
when i use the command 'adnet_demo' to test the demo

How can i solve it ?

**Comment by ZongweiZhou1** [comment]
OK, I have found the test code in zip file and now i'm testing.

**Comment by anilsh** [comment]
My precision is coming out to be 1.0 on Freeman1 dataset. Is it correct?

**Comment by hellbell** [comment]
That was a typo and fixed. Thanks!
