### ISSUE TITLE
the error  "FILTERS are larger than the DATA (including padding)."  during the training

### ISSUE THREAD

**Issue by deeplearnerJHB** [hellbell/ADNet#5]
When i train the  net , i meet this error "FILTERS are larger than the DATA (including padding)." which  makes me very confused. Can you tell me how to solve it? Thank you vert much!

**Comment by anilsh** [comment]
I am able to train it (at least for fewer iterations). Can you give more details about the error?

**Comment by Byuksell** [comment]
Can you explain how to train the network? It seems some .mat files are missing in the github. Which file should I run first? When I run adnet_train() I get "non-existent field 'train_dbs' "error. @anilsh @hellbell

**Comment by hellbell** [comment]
Can you explain more details about the error?

**Comment by jiweeo** [comment]
to download 'imagenet-vgg-m-conv1-3.mat' 
[click here](https://github.com/HyeonseobNam/MDNet/blob/master/models/imagenet-vgg-m-conv1-3.mat)
