### ISSUE TITLE
About adnet_compile.m

### ISSUE THREAD

**Issue by LinStan** [hellbell/ADNet#7]
Excuse me,I meet a problem:
       When I run the 'adnet_compile' append this mistake:
       This code is run on Win10 64bit, MATLAB 2016a, and Cuda-9.1 with NVIDIA GTX 970M

Misuse of mex
MEX cannot find the library 'nppi' specified with the -l option.
  MEX finds a file with one of the following names:
  Nppi.lib
  Libnppi.lib
  Use the -L option to specify the path to this library.

Error build_cropRectanglesMex_on_windows (line 39)
Mex(mopts{:}) ;

Error run (line 96)
Evalin('caller', [script ';']);

Error adnet_compile (line 23)
     Run build_cropRectanglesMex_on_windows.m

Could you help me? Thanks!

**Comment by LinStan** [comment]
I have been solved this problem.
It's because of my cuda don't Install correctly.
You should install cuda8.0 or lower

**Comment by hellbell** [comment]
Thanks. Close this issue.
