### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by akhilapoosa** [hellbell/ADNet#8]
I'm new to deep learning. I would like to know how this code works and how to train this code in matlab. Thanks in advance.

**Comment by aseuteurideu** [comment]
Assuming you have compiled matconvnet with `adnet_compile` as written in the README. 
As I remember what I did just couple days ago,
1. download the dataset (VOT2013, VOT2014, and VOT2015)
2. change the directory in utils/get_benchmark_path.m to your dataset directory
3. download [imagenet-vgg-m-conv1-3.mat](https://github.com/HyeonseobNam/MDNet/blob/master/models/imagenet-vgg-m-conv1-3.mat) and put it inside model folder
4. `adnet_train` in Matlab terminal
5. drink wine while waiting for the training to be finished
