### ISSUE TITLE
About test result

### ISSUE THREAD

**Issue by chenyanyin** [hellbell/ADNet#9]
Does anyone test the results with the updated model? My result on the OTB-100 is 0.574, but the result in the paper is 0.646. Does the test environment affect the result so much?

**Comment by aseuteurideu** [comment]
My result with 20px precision is also different from the paper. The paper reported 88.0 (or 85.1 in ADNet fast) while I got 78.17. Looking at the parameters in init_params.m , seems it is closer to ADNet fast parameters, but still lot of different.

Actually I think, one thing that can make the difference in the result is the redetection part. But I didn't expect that much different. May be, unluckily, when I tested, the redetection failed in the beginning so it affected the precision a lot. Currently I am trying to test couple of times to see if the result is fluctuating a lot, but it may takes time.

**Comment by deeplearnerJHB** [comment]
The result shown in the paper uses the vot + alov. But in this code, the author seems to just use the vot videos to train. I doubt that the uploaded model parameters also just uses the 58 vot videos, which is why the performance is lower than the one in paper.
